version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn logserver.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logserver.rule=Host(`numatrace.numatixsolutions.com`)"
      - "traefik.http.routers.logserver.entrypoints=websecure"
      - "traefik.http.routers.logserver.tls.certresolver=myresolver"
