# Generated by Django 5.1.7 on 2025-06-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner_email',
            new_name='developer_email',
        ),
    ]
